# NFC West
"ARI": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png"
"SF":  "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png"
"SEA": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png"
"LAR": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"  # Rams
"LA":  "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"  # alias

# NFC East
"DAL": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png"
"PHI": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png"
"NYG": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png"
"WAS": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"  # Commanders
"WSH": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"  # alias

# NFC North
"GB":  "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png"
"CHI": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png"
"DET": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png"
"MIN": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png"

# NFC South
"TB":  "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png"
"NO":  "https://a.espncdn.com/i/teamlogos/nfl/500/no.png"
"ATL": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png"
"CAR": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png"

# AFC West
"KC":  "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png"
"LAC": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png"
"LV":  "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png"
"DEN": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png"

# AFC East
"BUF": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png"
"MIA": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png"
"NE":  "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png"
"NYJ": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png"

# AFC North
"BAL": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png"
"CIN": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png"
"CLE": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png"
"PIT": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png"

# AFC South
"JAX": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png"
"JAC": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png"  # alias
"IND": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png"
"TEN": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png"
"HOU": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"
